project:
  type: website
  output-dir: docs

website:
  title: "Degrees of Freedom Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - ChemE.qmd
      - Rocketry.qmd
  sidebar:
    contents: auto
  
format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual
