project:
  type: website
  output-dir: docs

website:
  title: "Degrees of Freedom Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - ChemE.qmd
      - Rocketry.qmd
      - href: samples.qmd
        text: Samples


format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

