project:
  type: website
  output-dir: docs

website:
  title: "Degrees of Freedom Project"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - ChemE.qmd
      - Rocketry.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Chem E"
        contents:
          - ChemE.qmd
          - ChemE/ChEIntro.qmd
          - ChemE/Balances.qmd
      - section: "Rockets"
        contents:
          - Rocketry.qmd
          - rocket/Barometric Altitude.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual
