---
title: "Balances and Systems"
author: "DOFPro Group"
---

{{< video https://www.youtube.com/watch?v=Tp9P29KKw-k&list=PL1lnrwjgo31gb1NFBQy03i7ZXaccVD4xk&index=15&pp=iAQB >}}

> “Engineering is solving story problems where you often have to make up the story.”

> “Bookkeeping is just arithmetic and definitions, but it needs to be done correctly.”

> “There are many ways to solve a problem correctly. You want to develop a systematic approach, and not treat each problem as an isolated issue.”

## First – Define Your System

1.  Transient — The values of process variables are changing with time.

2.  SteadyState —The values of process variables do not change with time but may change with position. (What EE’s call a DC steady state)

3.  Batch (closed) — Throw stuff in. Wait. Pull products out.

4.  Semibatch — Neither batch nor continuous.

5.  Continuous (open) — Continually throw stuff in and pull stuff out.

## Control Volume

Sometimes for an open system, whether transient or steady state, the system boundary has a fixed volume and the different parts of the system maintain their relative positions. This fixed-volume boundary is known as a *control volume*. Inputs Outputs Control Volume (C.V.)

## The General Balance Equation

$$ \mathrm{Input + Generation = Output + Consumption + Accumulation} $$

-   All entities which can enter or exit a system are subject to the general balance equation.

-   For conserved quantities (energy, mass, atoms) the consumption and generation terms are zero

-   For steady-state systems the accumulation is zero.

## Differential or Integral

-   *Differential* Balances

    -   All terms in the balance are rate terms e.g., mol/s, gal/hr, pg/yr.

    -   Usually used for continuous processes.

-   *Integral* Balances

    -   All terms in the balance are amounts e.g., mol, gal, pg.

    -   Usually used for batch processes.

## Intensive and Extensive Properties

A property of a substance that *does not* depend on the mass or moles of a substance is an *intensive* property (such as temperature, pressure, density, or composition).

A property of a substance that *does* depend on the mass or moles of a substance is an *extensive* property (such as volume or weight).

It is quite frequently useful to define an intensive property that is related to the extensive property. These intensive properties are specific (or molar) properties and are usually indicated by a circumflex, e.g., specific volume. $\hat{V} = V/m$

## Definitions

PFD

:   Process Flow Diagram or flowsheet. A schematic drawing of the mixers, dividers, separators and reactors used in the process.

Recycle

:   Part of a product stream is returned to the feed of a process.

Bypass

:   Part of the feed is routed around a process and mixed with the product.

Purge

:   A stream used to prevent buildup of trace components in a recycle loop.

Tie Component

:   A component of the feed which is unchanged by a process. Often useful for calculations but never necessary.

Overall Balance

:   Treating a PFD as a black box with only inputs and outputs.

## One Useful Technique

1\. Draw a flowchart and fill in all given variable values.

2\. Choose a basis of calculation (usually an amount or flow rate of one of the process streams).

3\. Label unknown stream variables on the chart. Use a consistent system of labeling.

4\. Convert stream volumes or volumetric flow rates to mass or molar flow rates.

5\. Convert mixed mass and mole units to either all mass or all mole units.

6\. Write material balance equations.

7\. Write other problem constraints as equations.

8\. Do a Degree-of-Freedom analysis. Count the number of unknowns and the number of independent equations. Are they equal? What did you forget?

9\. Solve the equations.

10.Convert the answers to the desired units.

## Speed Tips

1\. Don’t solve for everything.

2\. Write equations in order of number of unknowns from fewest to most.

3\. Try overall balances first.

4\. Check out tie components.

5\. Remember mole fractions or mass fractions add up to 1.

6\. Usually, solving a recycle loop requires a complete set of equations around the loop.
