---
title: "Introduction"
author: "DOFPro group"
---

# Overview of Chemical and Thermal Processes

## Engineering Principles Discussed

-   Engineering Basics
    -   Statistics, Measurements, and Calculations
    -   Process Data and Variables, such as Pressure, Temperature, Mass, Moles, etc.
    -   Converting among systems of units
    -   Dimensionless numbers
-   System Definition
    -   Open or Closed
    -   Transient or Steady State
-   Material Balances
    -   Mass Balances
    -   Mole Balances
    -   Equations of State and Phase Equilibria
-   Energy Balances or the 1st Law of Thermodynamics
-   Entropy Balances or the 2nd Law of Thermodynamics
-   Thermodynamic Efficiency and the Combined 1st and 2nd Laws

## Why Chemical and Thermal Processes?

The principles in Chemical and Thermal Processes are applicable in

-   [Chemical Engineering](https://en.wikipedia.org/wiki/Chemical_engineering)
-   [Petroleum Engineering](https://en.wikipedia.org/wiki/Petroleum_engineering)
-   [Mechanical Engineering](https://en.wikipedia.org/wiki/Mechanical_engineering)
-   [Materials Engineering](https://en.wikipedia.org/wiki/Materials_science)
-   [Bioengineering](https://en.wikipedia.org/wiki/Biological_engineering)
-   [Environmental Engineering](https://en.wikipedia.org/wiki/Environmental_engineering)
-   [Energy Engineering](https://en.wikipedia.org/wiki/Energy_engineering)
-   [Sustainability](https://en.wikipedia.org/wiki/Sustainability)
-   [Manufacturing Engineering](https://en.wikipedia.org/wiki/Manufacturing_engineering)
-   [Industrial Engineering](https://en.wikipedia.org/wiki/Industrial_engineering)
-   [Marine](https://en.wikipedia.org/wiki/Marine_engineering) and [Aerospace Engineering](https://en.wikipedia.org/wiki/Aerospace_engineering)
